spring.application.name=api

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_NAME:nombre_bd}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:contraseña}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# ddl-auto: 'update' modificará la BD automáticamente según nuestras @Entity.
# Es ideal para desarrollo rápido, aunque en producción usaríamos migraciones (Flyway/Liquibase).
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL reales en la consola de IntelliJ (imprescindible para debugear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# BUENA PRÁCTICA: Desactivar Open Session In View (OSIV) para rendimiento profesional
spring.jpa.open-in-view=false
