spring.application.name=api

# ===================================================================
# CONFIGURACI�N DE LA BASE DE DATOS (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_NAME:nombre_bd}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:contrase�a}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACI�N DE JPA / HIBERNATE
# ===================================================================
# ddl-auto: 'update' modificar� la BD autom�ticamente seg�n nuestras @Entity.
# Es ideal para desarrollo r�pido, aunque en producci�n usar�amos migraciones (Flyway/Liquibase).
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL reales en la consola de IntelliJ (imprescindible para debugear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# BUENA PR�CTICA: Desactivar Open Session In View (OSIV) para rendimiento profesional
spring.jpa.open-in-view=false

# ===================================================================
# CONFIGURACIÓN JWT
# ===================================================================
# Clave secreta en Base64 (mínimo 256 bits). Cámbiala en producción.
jwt.secret=dGhpcyBpcyBhIHN1cGVyIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBzaWduaW5nITEyMw==
# Expiración del token en milisegundos (86400000 = 24 horas)
jwt.expiration=86400000
